server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/index.html $uri.html =404;
    }

    location /rechner {
        alias /usr/share/nginx/html/rechner;
        try_files $uri $uri/index.html =404;
    }
}
